server:
  port: 8980
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://111.161.122.204:56441/policy?useUnicode=true&characterEncoding=utf8
      username: policy
      password: NSKi6xM87jpK4PTL
      initial-size: 1
      min-idle: 1
      max-active: 20
  redis:
    cluster:
      nodes:
        - 150.158.128.134:9001
        - 150.158.128.134:9002
        - 150.158.128.134:9003
        - 150.158.128.134:9004
        - 150.158.128.134:9005
        - 150.158.128.134:9006

mybatis:
    type-aliases-package: com/example/architecture/demos/web/entity
    mapper-locations: /mapper/*.xml